language: node_js
node_js:
- 10
cache:
  directories:
  - "$HOME/.npm"

before_install:
- echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc

script:
  - npm run build-staging
  - npm run build-production

after_success:
  - npm run semantic-release
